### ISSUE TITLE
Let's merge two repos!

### ISSUE THREAD

**Issue by ericmjl** [parsing-science/ps-toolkit#7]
Hi Nicole!

Great talk at PyData NYC! I have a Bayesian analysis recipes repository, which implements a number of different custom Bayesian models, and I'd love to convert them to the scikit-learn-compatible format that you've shown in this repo. What do you think about renaming ps-toolkit to something like a "pymc_models" package?

Cheers,
Eric

**Comment by springcoil** [comment]
Plus one for this :)

**Comment by parsing-science** [comment]
@ericmjl: I kept meaning to write to you! I released pymc3_models (https://github.com/parsing-science/pymc3_models) so you should definitely add your models to that package instead. 

I'm going to close this issue. Hope to see some PR's from you soon!
